#!/usr/bin/env python3
"""Reconcile the SA3 Lightning budget from SETTLED job costs (GPU + CPU), not ledger estimates.

Gabriel (2026-08-22): the hard cap of 5 cr applies to TOTAL billable Lightning spend, because CPU
jobs also consume credits. Maintain three counters — SA3_GPU_credits, SA3_CPU_credits,
SA3_TOTAL_Lightning_credits — and never call a total that includes CPU "GPU all-time".

Queries every job in the teamspace, keeps those whose name matches --prefix (default "sa3-"),
reads each job's settled `total_cost` and machine, classifies GPU vs CPU, and writes a markdown
table + the three counters. Run with the cloudspace python that has lightning_sdk:

    /home/zeus/miniconda3/envs/cloudspace/bin/python scripts/sa3/reconcile_budget.py \
        --out docs/sa3/budget_reconciliation.md
"""
from __future__ import annotations
import argparse, sys

CAP = 5.0  # SA3 hard cap (TOTAL billable Lightning), Gabriel


def reconcile(prefix, teamspace, org):
    from lightning_sdk import Teamspace
    ts = Teamspace(name=teamspace, org=org)
    rows = []
    for j in ts.jobs:
        try:
            name = j.name
        except Exception:
            continue
        if not name.startswith(prefix):
            continue
        mach = str(getattr(j, "machine", "") or "")
        status = str(j.status)
        cost = float(getattr(j, "total_cost", 0.0) or 0.0)
        is_cpu = "CPU" in mach.upper()
        rows.append({"name": name, "machine": mach, "status": status, "cost": cost, "is_cpu": is_cpu})
    rows.sort(key=lambda r: r["name"])
    gpu = sum(r["cost"] for r in rows if not r["is_cpu"])
    cpu = sum(r["cost"] for r in rows if r["is_cpu"])
    total = gpu + cpu
    return rows, {"SA3_GPU_credits": round(gpu, 4), "SA3_CPU_credits": round(cpu, 4),
                  "SA3_TOTAL_Lightning_credits": round(total, 4), "hard_cap": CAP,
                  "headroom_TOTAL": round(CAP - total, 4), "n_jobs": len(rows)}


def to_markdown(rows, c):
    L = ["# SA3 budget reconciliation (settled Lightning costs)", "",
         "Generated by `scripts/sa3/reconcile_budget.py` from each job's settled `total_cost`.",
         "The hard cap of **5 cr applies to TOTAL billable Lightning spend** (GPU + CPU).", "",
         "| job | machine | status | settled cr |", "| --- | --- | --- | --- |"]
    for r in rows:
        L.append(f"| {r['name']} | {r['machine']} | {r['status']} | {r['cost']:.4f} |")
    L += ["", "## Counters",
          f"* **SA3_GPU_credits** = {c['SA3_GPU_credits']:.4f}",
          f"* **SA3_CPU_credits** = {c['SA3_CPU_credits']:.4f}",
          f"* **SA3_TOTAL_Lightning_credits** = {c['SA3_TOTAL_Lightning_credits']:.4f}",
          f"* hard cap (TOTAL) = {c['hard_cap']:.1f}  →  headroom = **{c['headroom_TOTAL']:.4f} cr**",
          f"* jobs reconciled = {c['n_jobs']}"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prefix", default="sa3-")
    ap.add_argument("--teamspace", default="general")
    ap.add_argument("--org", default="independentaudioresearch")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    rows, c = reconcile(a.prefix, a.teamspace, a.org)
    md = to_markdown(rows, c)
    if a.out:
        import os
        os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
        open(a.out, "w").write(md)
    print(md)
    import json
    print("COUNTERS", json.dumps(c))
    return 0


if __name__ == "__main__":
    sys.exit(main())
